package CompressionProject;
import Model.IconTextRenderer;
import java.awt.event.MouseAdapter;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionListener;
import javax.accessibility.AccessibleContext;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
public class GUI extends javax.swing.JFrame {
    
    public GUI() {
        FlatLightLaf.setup();
        initComponents();
        deCompressBtn.setVisible(false); 
        toCompressTable.setRowHeight(24);
    }
    
    public java.io.File[] getSelectedFilesFromDialog(){
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setDialogTitle("Kérem válasszon ki fájlokat és/vagy mappákat");
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            return chooser.getSelectedFiles();
        }
        return null;
    }
    
    public void displayErrorMessage(String errorMessage){
        JOptionPane.showMessageDialog(this, errorMessage);
    }
    
    public void setTableModel(AbstractTableModel tableModel){
        toCompressTable.setModel(tableModel);
    }
    
    public void addPlusButtonListener(ActionListener actionListener){
        addElementToCompressBtn.addActionListener(actionListener);
    }
    
    public void addMinusButtonListener(ActionListener actionListener){
        removeElementToCompressBtn.addActionListener(actionListener);
    }
    
    public void addTableMouseListener(MouseAdapter mouseAdapter){
        toCompressTable.addMouseListener(mouseAdapter);
    }
    
    public void addBackButtonListener(ActionListener actionListener){
        backButton.addActionListener(actionListener);
    }
    
    public void addNavigationTextFieldListener(ActionListener actionListener){
        navigationTextField.addActionListener(actionListener);
    }
    
    public void setNavigationTextField(String text){
        navigationTextField.setText(text);
    }
    
    public String getNavigationTextFieldValue(){
        return navigationTextField.getText();
    }
    
    public int[] getSelectedTableRows(){
        return toCompressTable.getSelectedRows();
    }
    
    public void setTableColumnModel(int columnIndex, DefaultTableCellRenderer renderer){
        toCompressTable.getColumnModel().getColumn(columnIndex).setCellRenderer(renderer);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        navigationTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        addElementToCompressBtn = new javax.swing.JButton();
        removeElementToCompressBtn = new javax.swing.JButton();
        CompressBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        toCompressTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        chooseFilePanel = new javax.swing.JPanel();
        deCompressBtn = new javax.swing.JButton();
        chooseCompressedFileBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        deCompressTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setForeground(java.awt.SystemColor.window);
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-left.png"))); // NOI18N

        navigationTextField.setText("\\");

            addElementToCompressBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/package-variant-plus(1).png"))); // NOI18N
            addElementToCompressBtn.setText("<html>Fájl/Mappa<br>hozzáadása");
            addElementToCompressBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            addElementToCompressBtn.setVerifyInputWhenFocusTarget(false);
            addElementToCompressBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

            removeElementToCompressBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/package-variant-minus.png"))); // NOI18N
            removeElementToCompressBtn.setText("<html>Fájl/Mappa<br>eltávolítása");
            removeElementToCompressBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            removeElementToCompressBtn.setVerifyInputWhenFocusTarget(false);
            removeElementToCompressBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

            CompressBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/package-variant-closed.png"))); // NOI18N
            CompressBtn.setText("Tömörítés");
            CompressBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            CompressBtn.setVerifyInputWhenFocusTarget(false);
            CompressBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

            toCompressTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String [] {
                    "Név és kiterjesztés", "Létrehozás dátuma", "Módosítás dátuma"
                }
            ));
            jScrollPane1.setViewportView(toCompressTable);

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CompressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addElementToCompressBtn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeElementToCompressBtn)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(addElementToCompressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(removeElementToCompressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CompressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(51, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(backButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(navigationTextField)
                    .addContainerGap())
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backButton)
                        .addComponent(navigationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, Short.MAX_VALUE)
            );

            jTabbedPane2.addTab("Tömörítés", jPanel1);

            deCompressBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/package-variant.png"))); // NOI18N
            deCompressBtn.setText("<html><center>Kiválasztott <br>fájlok és mappák <br>kibontása");
            deCompressBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            deCompressBtn.setVerifyInputWhenFocusTarget(false);
            deCompressBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            deCompressBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    deCompressBtnActionPerformed(evt);
                }
            });

            chooseCompressedFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/package-variant-closed.png"))); // NOI18N
            chooseCompressedFileBtn.setText("<html><center>Kibontandó fájl <br>kiválasztása");
            chooseCompressedFileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            chooseCompressedFileBtn.setVerifyInputWhenFocusTarget(false);
            chooseCompressedFileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            chooseCompressedFileBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    chooseCompressedFileBtnActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout chooseFilePanelLayout = new javax.swing.GroupLayout(chooseFilePanel);
            chooseFilePanel.setLayout(chooseFilePanelLayout);
            chooseFilePanelLayout.setHorizontalGroup(
                chooseFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooseFilePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(chooseFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chooseCompressedFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deCompressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            chooseFilePanelLayout.setVerticalGroup(
                chooseFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooseFilePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(chooseCompressedFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(deCompressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE))
            );

            deCompressTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String [] {
                    "Név és kiterjesztés", "Létrehozás dátuma", "Módosítás dátuma"
                }
            ));
            jScrollPane2.setViewportView(deCompressTable);

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(chooseFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(chooseFilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            jTabbedPane2.addTab("Kibontás", jPanel2);

            jLabel1.setText("Készítette: Bognár Vilmos Zsolt");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(500, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(314, Short.MAX_VALUE))
            );

            jTabbedPane2.addTab("Névjegy", jPanel3);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void deCompressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deCompressBtnActionPerformed
        
    }//GEN-LAST:event_deCompressBtnActionPerformed

    private void chooseCompressedFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseCompressedFileBtnActionPerformed
        
    }//GEN-LAST:event_chooseCompressedFileBtnActionPerformed

    public JRootPane getRootPane() {
        return rootPane;
    }

    public boolean isRootPaneCheckingEnabled() {
        return rootPaneCheckingEnabled;
    }

    /**
     * @param args the command line arguments
     */
    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompressBtn;
    private javax.swing.JButton addElementToCompressBtn;
    private javax.swing.JButton backButton;
    private javax.swing.JButton chooseCompressedFileBtn;
    private javax.swing.JPanel chooseFilePanel;
    private javax.swing.JButton deCompressBtn;
    private javax.swing.JTable deCompressTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField navigationTextField;
    private javax.swing.JButton removeElementToCompressBtn;
    private javax.swing.JTable toCompressTable;
    // End of variables declaration//GEN-END:variables
}
